// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: tide.proto

package tide

import (
	messenger "ecos/messenger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterStatus_Status int32

const (
	ClusterStatus_OFFLINE ClusterStatus_Status = 0
	ClusterStatus_ONLINE  ClusterStatus_Status = 1
)

// Enum value maps for ClusterStatus_Status.
var (
	ClusterStatus_Status_name = map[int32]string{
		0: "OFFLINE",
		1: "ONLINE",
	}
	ClusterStatus_Status_value = map[string]int32{
		"OFFLINE": 0,
		"ONLINE":  1,
	}
)

func (x ClusterStatus_Status) Enum() *ClusterStatus_Status {
	p := new(ClusterStatus_Status)
	*p = x
	return p
}

func (x ClusterStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tide_proto_enumTypes[0].Descriptor()
}

func (ClusterStatus_Status) Type() protoreflect.EnumType {
	return &file_tide_proto_enumTypes[0]
}

func (x ClusterStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterStatus_Status.Descriptor instead.
func (ClusterStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_tide_proto_rawDescGZIP(), []int{0, 0}
}

type Result_Status int32

const (
	Result_SUCCESS Result_Status = 0
	Result_PENDING Result_Status = 1
	Result_FAIL    Result_Status = -1
)

// Enum value maps for Result_Status.
var (
	Result_Status_name = map[int32]string{
		0:  "SUCCESS",
		1:  "PENDING",
		-1: "FAIL",
	}
	Result_Status_value = map[string]int32{
		"SUCCESS": 0,
		"PENDING": 1,
		"FAIL":    -1,
	}
)

func (x Result_Status) Enum() *Result_Status {
	p := new(Result_Status)
	*p = x
	return p
}

func (x Result_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tide_proto_enumTypes[1].Descriptor()
}

func (Result_Status) Type() protoreflect.EnumType {
	return &file_tide_proto_enumTypes[1]
}

func (x Result_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result_Status.Descriptor instead.
func (Result_Status) EnumDescriptor() ([]byte, []int) {
	return file_tide_proto_rawDescGZIP(), []int{1, 0}
}

type ClusterStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*ClusterStatus_Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *ClusterStatus) Reset() {
	*x = ClusterStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tide_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatus) ProtoMessage() {}

func (x *ClusterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_tide_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatus.ProtoReflect.Descriptor instead.
func (*ClusterStatus) Descriptor() ([]byte, []int) {
	return file_tide_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterStatus) GetNodes() []*ClusterStatus_Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Result_Status `protobuf:"varint,1,opt,name=status,proto3,enum=messenger.Result_Status" json:"status,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tide_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_tide_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_tide_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetStatus() Result_Status {
	if x != nil {
		return x.Status
	}
	return Result_SUCCESS
}

type ClusterStatus_Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID        string               `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	IpAddr      string               `protobuf:"bytes,2,opt,name=IpAddr,proto3" json:"IpAddr,omitempty"`
	StoragePath string               `protobuf:"bytes,3,opt,name=StoragePath,proto3" json:"StoragePath,omitempty"`
	Capacity    uint64               `protobuf:"varint,4,opt,name=Capacity,proto3" json:"Capacity,omitempty"`
	Status      ClusterStatus_Status `protobuf:"varint,5,opt,name=Status,proto3,enum=messenger.ClusterStatus_Status" json:"Status,omitempty"`
}

func (x *ClusterStatus_Node) Reset() {
	*x = ClusterStatus_Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tide_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterStatus_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatus_Node) ProtoMessage() {}

func (x *ClusterStatus_Node) ProtoReflect() protoreflect.Message {
	mi := &file_tide_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatus_Node.ProtoReflect.Descriptor instead.
func (*ClusterStatus_Node) Descriptor() ([]byte, []int) {
	return file_tide_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ClusterStatus_Node) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *ClusterStatus_Node) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

func (x *ClusterStatus_Node) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *ClusterStatus_Node) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *ClusterStatus_Node) GetStatus() ClusterStatus_Status {
	if x != nil {
		return x.Status
	}
	return ClusterStatus_OFFLINE
}

var File_tide_proto protoreflect.FileDescriptor

var file_tide_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x69, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x65,
	0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x93, 0x02, 0x0a, 0x0d, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x33, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x1a, 0xa9, 0x01, 0x0a, 0x04, 0x4e, 0x6f,
	0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x70, 0x41, 0x64, 0x64, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x70, 0x41, 0x64, 0x64, 0x72, 0x12, 0x20,
	0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x37, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x21, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x22, 0x71, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x35, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50,
	0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c,
	0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x32, 0xc4, 0x01, 0x0a, 0x08,
	0x4e, 0x6f, 0x64, 0x65, 0x54, 0x69, 0x64, 0x65, 0x12, 0x46, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72,
	0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00,
	0x12, 0x34, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x1a,
	0x11, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x00, 0x28, 0x01, 0x12, 0x3a, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65,
	0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67,
	0x65, 0x72, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x11, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x65, 0x63, 0x6f, 0x73, 0x2f, 0x74, 0x69, 0x64, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tide_proto_rawDescOnce sync.Once
	file_tide_proto_rawDescData = file_tide_proto_rawDesc
)

func file_tide_proto_rawDescGZIP() []byte {
	file_tide_proto_rawDescOnce.Do(func() {
		file_tide_proto_rawDescData = protoimpl.X.CompressGZIP(file_tide_proto_rawDescData)
	})
	return file_tide_proto_rawDescData
}

var file_tide_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tide_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tide_proto_goTypes = []interface{}{
	(ClusterStatus_Status)(0),    // 0: messenger.ClusterStatus.Status
	(Result_Status)(0),           // 1: messenger.Result.Status
	(*ClusterStatus)(nil),        // 2: messenger.ClusterStatus
	(*Result)(nil),               // 3: messenger.Result
	(*ClusterStatus_Node)(nil),   // 4: messenger.ClusterStatus.Node
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
	(*messenger.Block)(nil),      // 6: messenger.Block
	(*messenger.ObjectInfo)(nil), // 7: messenger.ObjectInfo
}
var file_tide_proto_depIdxs = []int32{
	4, // 0: messenger.ClusterStatus.nodes:type_name -> messenger.ClusterStatus.Node
	1, // 1: messenger.Result.status:type_name -> messenger.Result.Status
	0, // 2: messenger.ClusterStatus.Node.Status:type_name -> messenger.ClusterStatus.Status
	5, // 3: messenger.NodeTide.GetClusterStatus:input_type -> google.protobuf.Empty
	6, // 4: messenger.NodeTide.SendBlock:input_type -> messenger.Block
	7, // 5: messenger.NodeTide.SendMetaData:input_type -> messenger.ObjectInfo
	2, // 6: messenger.NodeTide.GetClusterStatus:output_type -> messenger.ClusterStatus
	3, // 7: messenger.NodeTide.SendBlock:output_type -> messenger.Result
	3, // 8: messenger.NodeTide.SendMetaData:output_type -> messenger.Result
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tide_proto_init() }
func file_tide_proto_init() {
	if File_tide_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tide_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tide_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tide_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterStatus_Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tide_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tide_proto_goTypes,
		DependencyIndexes: file_tide_proto_depIdxs,
		EnumInfos:         file_tide_proto_enumTypes,
		MessageInfos:      file_tide_proto_msgTypes,
	}.Build()
	File_tide_proto = out.File
	file_tide_proto_rawDesc = nil
	file_tide_proto_goTypes = nil
	file_tide_proto_depIdxs = nil
}
