// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: monitor.proto

package watcher

import (
	infos "ecos/edge-node/infos"
	_ "ecos/messenger/common"
	timestamp "ecos/utils/timestamp"
	encoding_binary "encoding/binary"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeStatusReport_Role int32

const (
	NodeStatusReport_UNKNOWN  NodeStatusReport_Role = 0
	NodeStatusReport_LEADER   NodeStatusReport_Role = 1
	NodeStatusReport_FOLLOWER NodeStatusReport_Role = 2
	NodeStatusReport_LEARNER  NodeStatusReport_Role = 3
)

var NodeStatusReport_Role_name = map[int32]string{
	0: "UNKNOWN",
	1: "LEADER",
	2: "FOLLOWER",
	3: "LEARNER",
}

var NodeStatusReport_Role_value = map[string]int32{
	"UNKNOWN":  0,
	"LEADER":   1,
	"FOLLOWER": 2,
	"LEARNER":  3,
}

func (x NodeStatusReport_Role) String() string {
	return proto.EnumName(NodeStatusReport_Role_name, int32(x))
}

func (NodeStatusReport_Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{0, 0}
}

type PipelineReport_State int32

const (
	PipelineReport_UNKNOWN    PipelineReport_State = 0
	PipelineReport_OK         PipelineReport_State = 1
	PipelineReport_DOWN_GRADE PipelineReport_State = 2
	PipelineReport_CHANGING   PipelineReport_State = 3
	PipelineReport_ERROR      PipelineReport_State = 4
)

var PipelineReport_State_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "DOWN_GRADE",
	3: "CHANGING",
	4: "ERROR",
}

var PipelineReport_State_value = map[string]int32{
	"UNKNOWN":    0,
	"OK":         1,
	"DOWN_GRADE": 2,
	"CHANGING":   3,
	"ERROR":      4,
}

func (x PipelineReport_State) String() string {
	return proto.EnumName(PipelineReport_State_name, int32(x))
}

func (PipelineReport_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{2, 0}
}

type ClusterReport_ClusterState int32

const (
	ClusterReport_UNKNOWN     ClusterReport_ClusterState = 0
	ClusterReport_HEALTH_OK   ClusterReport_ClusterState = 1
	ClusterReport_HEALTH_WARN ClusterReport_ClusterState = 2
	ClusterReport_HEALTH_ERR  ClusterReport_ClusterState = 3
)

var ClusterReport_ClusterState_name = map[int32]string{
	0: "UNKNOWN",
	1: "HEALTH_OK",
	2: "HEALTH_WARN",
	3: "HEALTH_ERR",
}

var ClusterReport_ClusterState_value = map[string]int32{
	"UNKNOWN":     0,
	"HEALTH_OK":   1,
	"HEALTH_WARN": 2,
	"HEALTH_ERR":  3,
}

func (x ClusterReport_ClusterState) String() string {
	return proto.EnumName(ClusterReport_ClusterState_name, int32(x))
}

func (ClusterReport_ClusterState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{3, 0}
}

type NodeStatusReport struct {
	NodeId               uint64                `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeUuid             string                `protobuf:"bytes,2,opt,name=node_uuid,json=nodeUuid,proto3" json:"node_uuid,omitempty"`
	Timestamp            *timestamp.Timestamp  `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	State                infos.NodeState       `protobuf:"varint,4,opt,name=state,proto3,enum=messenger.NodeState" json:"state,omitempty"`
	Status               *NodeStatus           `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Role                 NodeStatusReport_Role `protobuf:"varint,6,opt,name=role,proto3,enum=messenger.NodeStatusReport_Role" json:"role,omitempty"`
	Pipelines            []*PipelineReport     `protobuf:"bytes,7,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *NodeStatusReport) Reset()         { *m = NodeStatusReport{} }
func (m *NodeStatusReport) String() string { return proto.CompactTextString(m) }
func (*NodeStatusReport) ProtoMessage()    {}
func (*NodeStatusReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{0}
}
func (m *NodeStatusReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeStatusReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NodeStatusReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NodeStatusReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatusReport.Merge(m, src)
}
func (m *NodeStatusReport) XXX_Size() int {
	return m.Size()
}
func (m *NodeStatusReport) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatusReport.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatusReport proto.InternalMessageInfo

func (m *NodeStatusReport) GetNodeId() uint64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *NodeStatusReport) GetNodeUuid() string {
	if m != nil {
		return m.NodeUuid
	}
	return ""
}

func (m *NodeStatusReport) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *NodeStatusReport) GetState() infos.NodeState {
	if m != nil {
		return m.State
	}
	return infos.NodeState_UNKNOWN
}

func (m *NodeStatusReport) GetStatus() *NodeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *NodeStatusReport) GetRole() NodeStatusReport_Role {
	if m != nil {
		return m.Role
	}
	return NodeStatusReport_UNKNOWN
}

func (m *NodeStatusReport) GetPipelines() []*PipelineReport {
	if m != nil {
		return m.Pipelines
	}
	return nil
}

type NodeStatus struct {
	DiskAvailable        uint64   `protobuf:"varint,1,opt,name=disk_available,json=diskAvailable,proto3" json:"disk_available,omitempty"`
	DiskTotal            uint64   `protobuf:"varint,2,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	NetworkSpeed         uint64   `protobuf:"varint,3,opt,name=network_speed,json=networkSpeed,proto3" json:"network_speed,omitempty"`
	CpuPercent           float64  `protobuf:"fixed64,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsage          uint64   `protobuf:"varint,5,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryTotal          uint64   `protobuf:"varint,6,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	BlockCount           uint64   `protobuf:"varint,7,opt,name=block_count,json=blockCount,proto3" json:"block_count,omitempty"`
	MetaCount            uint64   `protobuf:"varint,8,opt,name=meta_count,json=metaCount,proto3" json:"meta_count,omitempty"`
	GoroutineCount       uint64   `protobuf:"varint,9,opt,name=goroutine_count,json=goroutineCount,proto3" json:"goroutine_count,omitempty"`
	MetaPipelineCount    uint64   `protobuf:"varint,10,opt,name=meta_pipeline_count,json=metaPipelineCount,proto3" json:"meta_pipeline_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeStatus) Reset()         { *m = NodeStatus{} }
func (m *NodeStatus) String() string { return proto.CompactTextString(m) }
func (*NodeStatus) ProtoMessage()    {}
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{1}
}
func (m *NodeStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NodeStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NodeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatus.Merge(m, src)
}
func (m *NodeStatus) XXX_Size() int {
	return m.Size()
}
func (m *NodeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatus proto.InternalMessageInfo

func (m *NodeStatus) GetDiskAvailable() uint64 {
	if m != nil {
		return m.DiskAvailable
	}
	return 0
}

func (m *NodeStatus) GetDiskTotal() uint64 {
	if m != nil {
		return m.DiskTotal
	}
	return 0
}

func (m *NodeStatus) GetNetworkSpeed() uint64 {
	if m != nil {
		return m.NetworkSpeed
	}
	return 0
}

func (m *NodeStatus) GetCpuPercent() float64 {
	if m != nil {
		return m.CpuPercent
	}
	return 0
}

func (m *NodeStatus) GetMemoryUsage() uint64 {
	if m != nil {
		return m.MemoryUsage
	}
	return 0
}

func (m *NodeStatus) GetMemoryTotal() uint64 {
	if m != nil {
		return m.MemoryTotal
	}
	return 0
}

func (m *NodeStatus) GetBlockCount() uint64 {
	if m != nil {
		return m.BlockCount
	}
	return 0
}

func (m *NodeStatus) GetMetaCount() uint64 {
	if m != nil {
		return m.MetaCount
	}
	return 0
}

func (m *NodeStatus) GetGoroutineCount() uint64 {
	if m != nil {
		return m.GoroutineCount
	}
	return 0
}

func (m *NodeStatus) GetMetaPipelineCount() uint64 {
	if m != nil {
		return m.MetaPipelineCount
	}
	return 0
}

type PipelineReport struct {
	PgId                 uint64               `protobuf:"varint,1,opt,name=pg_id,json=pgId,proto3" json:"pg_id,omitempty"`
	NodeIds              []uint64             `protobuf:"varint,2,rep,packed,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	State                PipelineReport_State `protobuf:"varint,3,opt,name=state,proto3,enum=messenger.PipelineReport_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PipelineReport) Reset()         { *m = PipelineReport{} }
func (m *PipelineReport) String() string { return proto.CompactTextString(m) }
func (*PipelineReport) ProtoMessage()    {}
func (*PipelineReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{2}
}
func (m *PipelineReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PipelineReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PipelineReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PipelineReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineReport.Merge(m, src)
}
func (m *PipelineReport) XXX_Size() int {
	return m.Size()
}
func (m *PipelineReport) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineReport.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineReport proto.InternalMessageInfo

func (m *PipelineReport) GetPgId() uint64 {
	if m != nil {
		return m.PgId
	}
	return 0
}

func (m *PipelineReport) GetNodeIds() []uint64 {
	if m != nil {
		return m.NodeIds
	}
	return nil
}

func (m *PipelineReport) GetState() PipelineReport_State {
	if m != nil {
		return m.State
	}
	return PipelineReport_UNKNOWN
}

type ClusterReport struct {
	State                ClusterReport_ClusterState `protobuf:"varint,1,opt,name=state,proto3,enum=messenger.ClusterReport_ClusterState" json:"state,omitempty"`
	ClusterInfo          *infos.ClusterInfo         `protobuf:"bytes,2,opt,name=cluster_info,json=clusterInfo,proto3" json:"cluster_info,omitempty"`
	Nodes                []*NodeStatusReport        `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Pipelines            []*PipelineReport          `protobuf:"bytes,4,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ClusterReport) Reset()         { *m = ClusterReport{} }
func (m *ClusterReport) String() string { return proto.CompactTextString(m) }
func (*ClusterReport) ProtoMessage()    {}
func (*ClusterReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{3}
}
func (m *ClusterReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClusterReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterReport.Merge(m, src)
}
func (m *ClusterReport) XXX_Size() int {
	return m.Size()
}
func (m *ClusterReport) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterReport.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterReport proto.InternalMessageInfo

func (m *ClusterReport) GetState() ClusterReport_ClusterState {
	if m != nil {
		return m.State
	}
	return ClusterReport_UNKNOWN
}

func (m *ClusterReport) GetClusterInfo() *infos.ClusterInfo {
	if m != nil {
		return m.ClusterInfo
	}
	return nil
}

func (m *ClusterReport) GetNodes() []*NodeStatusReport {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *ClusterReport) GetPipelines() []*PipelineReport {
	if m != nil {
		return m.Pipelines
	}
	return nil
}

type StateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateRequest) Reset()         { *m = StateRequest{} }
func (m *StateRequest) String() string { return proto.CompactTextString(m) }
func (*StateRequest) ProtoMessage()    {}
func (*StateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{4}
}
func (m *StateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateRequest.Merge(m, src)
}
func (m *StateRequest) XXX_Size() int {
	return m.Size()
}
func (m *StateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StateRequest proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("messenger.NodeStatusReport_Role", NodeStatusReport_Role_name, NodeStatusReport_Role_value)
	proto.RegisterEnum("messenger.PipelineReport_State", PipelineReport_State_name, PipelineReport_State_value)
	proto.RegisterEnum("messenger.ClusterReport_ClusterState", ClusterReport_ClusterState_name, ClusterReport_ClusterState_value)
	proto.RegisterType((*NodeStatusReport)(nil), "messenger.NodeStatusReport")
	proto.RegisterType((*NodeStatus)(nil), "messenger.NodeStatus")
	proto.RegisterType((*PipelineReport)(nil), "messenger.PipelineReport")
	proto.RegisterType((*ClusterReport)(nil), "messenger.ClusterReport")
	proto.RegisterType((*StateRequest)(nil), "messenger.StateRequest")
}

func init() { proto.RegisterFile("monitor.proto", fileDescriptor_44174b7b2a306b71) }

var fileDescriptor_44174b7b2a306b71 = []byte{
	// 842 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc7, 0xe3, 0xd8, 0x49, 0xea, 0xe3, 0x24, 0xf5, 0xce, 0x42, 0xf1, 0xb6, 0xa2, 0x0d, 0x46,
	0x2b, 0x22, 0xa4, 0x75, 0x45, 0x00, 0x21, 0x16, 0x6e, 0x42, 0xeb, 0x4d, 0xab, 0x06, 0x67, 0x35,
	0xdb, 0xaa, 0x12, 0x37, 0x96, 0x6b, 0x4f, 0x83, 0x55, 0xdb, 0x63, 0x3c, 0x63, 0x56, 0x7b, 0xcb,
	0x53, 0xf0, 0x34, 0x88, 0x4b, 0x24, 0x6e, 0x78, 0x04, 0x54, 0x1e, 0x82, 0x5b, 0x34, 0x63, 0xbb,
	0x49, 0xc4, 0xb6, 0xd2, 0x5e, 0x9e, 0xff, 0xf9, 0xf9, 0xf8, 0xcc, 0xf9, 0x82, 0x41, 0x4a, 0xb3,
	0x98, 0xd3, 0xc2, 0xc9, 0x0b, 0xca, 0x29, 0xd2, 0x53, 0xc2, 0x18, 0xc9, 0x96, 0xa4, 0xd8, 0xed,
	0x87, 0x34, 0x4d, 0x69, 0x56, 0x39, 0x76, 0x8d, 0x38, 0xbb, 0xa6, 0xac, 0x36, 0xb6, 0x79, 0x9c,
	0x12, 0xc6, 0x83, 0x34, 0xaf, 0x85, 0xbd, 0x25, 0xa5, 0xcb, 0x84, 0x1c, 0x4a, 0xeb, 0xaa, 0xbc,
	0x3e, 0x24, 0x69, 0xce, 0xdf, 0x54, 0x4e, 0xfb, 0x17, 0x15, 0x4c, 0x8f, 0x46, 0xe4, 0x15, 0x0f,
	0x78, 0xc9, 0x30, 0xc9, 0x69, 0xc1, 0xd1, 0x07, 0xd0, 0xcb, 0x68, 0x44, 0xfc, 0x38, 0xb2, 0x94,
	0x91, 0x32, 0xd6, 0x70, 0x57, 0x98, 0xa7, 0x11, 0xda, 0x03, 0x5d, 0x3a, 0xca, 0x32, 0x8e, 0xac,
	0xf6, 0x48, 0x19, 0xeb, 0x78, 0x4b, 0x08, 0x17, 0x65, 0x1c, 0xa1, 0x09, 0xe8, 0x77, 0xbf, 0xb6,
	0xd4, 0x91, 0x32, 0x36, 0x26, 0xef, 0x39, 0x77, 0x29, 0x3b, 0xe7, 0x8d, 0x0f, 0xaf, 0x30, 0xf4,
	0x29, 0x74, 0x18, 0x0f, 0x38, 0xb1, 0xb4, 0x91, 0x32, 0x1e, 0x6e, 0xf0, 0x4d, 0x56, 0x04, 0x57,
	0x08, 0x7a, 0x06, 0x5d, 0x26, 0xb3, 0xb4, 0x3a, 0x32, 0xf8, 0xfb, 0x6f, 0x81, 0x4b, 0x86, 0x6b,
	0x08, 0x7d, 0x01, 0x5a, 0x41, 0x13, 0x62, 0x75, 0x65, 0xe4, 0xd1, 0xdb, 0x61, 0xf9, 0x5e, 0x07,
	0xd3, 0x84, 0x60, 0x49, 0xa3, 0xaf, 0x40, 0xcf, 0xe3, 0x9c, 0x24, 0x71, 0x46, 0x98, 0xd5, 0x1b,
	0xa9, 0x63, 0x63, 0xf2, 0x64, 0xed, 0xd3, 0x97, 0xb5, 0xaf, 0xfa, 0x10, 0xaf, 0x58, 0xfb, 0x39,
	0x68, 0x22, 0x0c, 0x32, 0xa0, 0x77, 0xe1, 0x9d, 0x79, 0x8b, 0x4b, 0xcf, 0x6c, 0x21, 0x80, 0xee,
	0xdc, 0x9d, 0x1e, 0xbb, 0xd8, 0x54, 0x50, 0x1f, 0xb6, 0x5e, 0x2c, 0xe6, 0xf3, 0xc5, 0xa5, 0x8b,
	0xcd, 0xb6, 0xc0, 0xe6, 0xee, 0x14, 0x7b, 0x2e, 0x36, 0x55, 0xfb, 0xdf, 0x36, 0xc0, 0x2a, 0x29,
	0xf4, 0x14, 0x86, 0x51, 0xcc, 0x6e, 0xfc, 0xe0, 0xe7, 0x20, 0x4e, 0x82, 0xab, 0x84, 0xd4, 0x5d,
	0x18, 0x08, 0x75, 0xda, 0x88, 0xe8, 0x43, 0x00, 0x89, 0x71, 0xca, 0x83, 0x44, 0x76, 0x43, 0xc3,
	0xba, 0x50, 0xce, 0x85, 0x80, 0x3e, 0x86, 0x41, 0x46, 0xf8, 0x6b, 0x5a, 0xdc, 0xf8, 0x2c, 0x27,
	0x24, 0x92, 0x2d, 0xd1, 0x70, 0xbf, 0x16, 0x5f, 0x09, 0x0d, 0x1d, 0x80, 0x11, 0xe6, 0xa5, 0x9f,
	0x93, 0x22, 0x24, 0x19, 0x97, 0x5d, 0x50, 0x30, 0x84, 0x79, 0xf9, 0xb2, 0x52, 0xd0, 0x47, 0xd0,
	0x4f, 0x49, 0x4a, 0x8b, 0x37, 0x7e, 0xc9, 0x82, 0x25, 0x91, 0xa5, 0xd7, 0xb0, 0x51, 0x69, 0x17,
	0x42, 0x5a, 0x43, 0xaa, 0x4c, 0xba, 0xeb, 0x48, 0x95, 0xcb, 0x01, 0x18, 0x57, 0x09, 0x0d, 0x6f,
	0xfc, 0x90, 0x96, 0x19, 0xb7, 0x7a, 0x92, 0x00, 0x29, 0x1d, 0x09, 0x45, 0xbc, 0x25, 0x25, 0x3c,
	0xa8, 0xfd, 0x5b, 0xd5, 0x5b, 0x84, 0x52, 0xb9, 0x3f, 0x81, 0xed, 0x25, 0x2d, 0x68, 0xc9, 0xe3,
	0x8c, 0xd4, 0x8c, 0x2e, 0x99, 0xe1, 0x9d, 0x5c, 0x81, 0x0e, 0x3c, 0x96, 0x71, 0x9a, 0xbe, 0xd4,
	0x30, 0x48, 0xf8, 0x91, 0x70, 0x35, 0x1d, 0x94, 0xbc, 0xfd, 0x9b, 0x02, 0xc3, 0xcd, 0x9e, 0xa2,
	0xc7, 0xd0, 0xc9, 0x97, 0xab, 0xd1, 0xd7, 0xf2, 0xe5, 0x69, 0x84, 0x9e, 0xc0, 0x56, 0xbd, 0x11,
	0xcc, 0x6a, 0x8f, 0xd4, 0xb1, 0x86, 0x7b, 0xd5, 0x4a, 0x30, 0xf4, 0x65, 0x33, 0xc2, 0xaa, 0x1c,
	0xb4, 0x83, 0x7b, 0xa7, 0xc5, 0x59, 0x9f, 0x66, 0xdb, 0x85, 0x8e, 0xb4, 0x37, 0x07, 0xa6, 0x0b,
	0xed, 0xc5, 0x99, 0xa9, 0xa0, 0x21, 0xc0, 0xf1, 0xe2, 0xd2, 0xf3, 0x67, 0x78, 0x7a, 0xec, 0x9a,
	0x6d, 0x31, 0x3c, 0x47, 0x27, 0x53, 0x6f, 0x76, 0xea, 0xcd, 0x4c, 0x15, 0xe9, 0xd0, 0x71, 0x31,
	0x5e, 0x60, 0x53, 0xb3, 0x7f, 0x6f, 0xc3, 0xe0, 0x28, 0x29, 0x19, 0x27, 0x45, 0x9d, 0xff, 0x37,
	0x4d, 0x3e, 0x8a, 0xcc, 0xe7, 0xe9, 0x5a, 0x3e, 0x1b, 0x60, 0x63, 0x6d, 0xec, 0xd8, 0xd7, 0xd0,
	0x0f, 0x2b, 0xd9, 0x17, 0x37, 0x45, 0x4e, 0x95, 0x31, 0xd9, 0xf9, 0x7f, 0x8c, 0xd3, 0xec, 0x9a,
	0x62, 0x23, 0x5c, 0x19, 0xe8, 0x33, 0xe8, 0x88, 0x92, 0x30, 0x4b, 0x95, 0x5b, 0xb3, 0xf7, 0xc0,
	0xc2, 0xe1, 0x8a, 0xdc, 0x5c, 0x36, 0xed, 0x1d, 0x96, 0xed, 0x0c, 0xfa, 0xeb, 0xd9, 0x6f, 0xd6,
	0x70, 0x00, 0xfa, 0x89, 0x3b, 0x9d, 0x9f, 0x9f, 0xf8, 0xb2, 0x94, 0xdb, 0x60, 0xd4, 0xe6, 0xe5,
	0x14, 0x7b, 0x66, 0x5b, 0xd4, 0xb6, 0x16, 0x5c, 0x2c, 0xb6, 0x6f, 0x08, 0xfd, 0xaa, 0x06, 0xe4,
	0xa7, 0x92, 0x30, 0x3e, 0xf9, 0x53, 0x81, 0xde, 0xf7, 0xd5, 0xe1, 0x45, 0xcf, 0xa1, 0x5b, 0x97,
	0xf5, 0xa1, 0xf7, 0xec, 0x3e, 0x5a, 0x73, 0x62, 0xc2, 0xca, 0x84, 0xdb, 0x2d, 0xf4, 0x2d, 0xa8,
	0x33, 0xc2, 0xd1, 0x8e, 0x53, 0xdd, 0x5f, 0xa7, 0xb9, 0xbf, 0x8e, 0x2b, 0xee, 0xef, 0xee, 0x43,
	0x01, 0xed, 0x16, 0x7a, 0x01, 0xe6, 0x8c, 0xf0, 0xcd, 0xd6, 0xde, 0x17, 0xca, 0xba, 0xaf, 0xc7,
	0x76, 0xeb, 0xbb, 0xf1, 0x1f, 0xb7, 0xfb, 0xca, 0x5f, 0xb7, 0xfb, 0xca, 0xdf, 0xb7, 0xfb, 0xca,
	0xaf, 0xff, 0xec, 0xb7, 0x7e, 0xd8, 0x21, 0x21, 0x65, 0x87, 0x24, 0x5a, 0x92, 0x67, 0xa2, 0x0d,
	0x87, 0xaf, 0x03, 0x1e, 0xfe, 0x48, 0x8a, 0xab, 0xae, 0x8c, 0xfa, 0xf9, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x04, 0x45, 0x1e, 0x95, 0x76, 0x06, 0x00, 0x00,
}

func (m *NodeStatusReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeStatusReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeStatusReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Pipelines) > 0 {
		for iNdEx := len(m.Pipelines) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pipelines[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMonitor(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.Role != 0 {
		i = encodeVarintMonitor(dAtA, i, uint64(m.Role))
		i--
		dAtA[i] = 0x30
	}
	if m.Status != nil {
		{
			size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMonitor(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.State != 0 {
		i = encodeVarintMonitor(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x20
	}
	if m.Timestamp != nil {
		{
			size, err := m.Timestamp.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMonitor(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NodeUuid) > 0 {
		i -= len(m.NodeUuid)
		copy(dAtA[i:], m.NodeUuid)
		i = encodeVarintMonitor(dAtA, i, uint64(len(m.NodeUuid)))
		i--
		dAtA[i] = 0x12
	}
	if m.NodeId != 0 {
		i = encodeVarintMonitor(dAtA, i, uint64(m.NodeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NodeStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.MetaPipelineCount != 0 {
		i = encodeVarintMonitor(dAtA, i, uint64(m.MetaPipelineCount))
		i--
		dAtA[i] = 0x50
	}
	if m.GoroutineCount != 0 {
		i = encodeVarintMonitor(dAtA, i, uint64(m.GoroutineCount))
		i--
		dAtA[i] = 0x48
	}
	if m.MetaCount != 0 {
		i = encodeVarintMonitor(dAtA, i, uint64(m.MetaCount))
		i--
		dAtA[i] = 0x40
	}
	if m.BlockCount != 0 {
		i = encodeVarintMonitor(dAtA, i, uint64(m.BlockCount))
		i--
		dAtA[i] = 0x38
	}
	if m.MemoryTotal != 0 {
		i = encodeVarintMonitor(dAtA, i, uint64(m.MemoryTotal))
		i--
		dAtA[i] = 0x30
	}
	if m.MemoryUsage != 0 {
		i = encodeVarintMonitor(dAtA, i, uint64(m.MemoryUsage))
		i--
		dAtA[i] = 0x28
	}
	if m.CpuPercent != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.CpuPercent))))
		i--
		dAtA[i] = 0x21
	}
	if m.NetworkSpeed != 0 {
		i = encodeVarintMonitor(dAtA, i, uint64(m.NetworkSpeed))
		i--
		dAtA[i] = 0x18
	}
	if m.DiskTotal != 0 {
		i = encodeVarintMonitor(dAtA, i, uint64(m.DiskTotal))
		i--
		dAtA[i] = 0x10
	}
	if m.DiskAvailable != 0 {
		i = encodeVarintMonitor(dAtA, i, uint64(m.DiskAvailable))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PipelineReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PipelineReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PipelineReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.State != 0 {
		i = encodeVarintMonitor(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x18
	}
	if len(m.NodeIds) > 0 {
		dAtA4 := make([]byte, len(m.NodeIds)*10)
		var j3 int
		for _, num := range m.NodeIds {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintMonitor(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x12
	}
	if m.PgId != 0 {
		i = encodeVarintMonitor(dAtA, i, uint64(m.PgId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ClusterReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClusterReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Pipelines) > 0 {
		for iNdEx := len(m.Pipelines) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pipelines[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMonitor(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Nodes) > 0 {
		for iNdEx := len(m.Nodes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Nodes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMonitor(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.ClusterInfo != nil {
		{
			size, err := m.ClusterInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMonitor(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.State != 0 {
		i = encodeVarintMonitor(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func encodeVarintMonitor(dAtA []byte, offset int, v uint64) int {
	offset -= sovMonitor(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NodeStatusReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NodeId != 0 {
		n += 1 + sovMonitor(uint64(m.NodeId))
	}
	l = len(m.NodeUuid)
	if l > 0 {
		n += 1 + l + sovMonitor(uint64(l))
	}
	if m.Timestamp != nil {
		l = m.Timestamp.Size()
		n += 1 + l + sovMonitor(uint64(l))
	}
	if m.State != 0 {
		n += 1 + sovMonitor(uint64(m.State))
	}
	if m.Status != nil {
		l = m.Status.Size()
		n += 1 + l + sovMonitor(uint64(l))
	}
	if m.Role != 0 {
		n += 1 + sovMonitor(uint64(m.Role))
	}
	if len(m.Pipelines) > 0 {
		for _, e := range m.Pipelines {
			l = e.Size()
			n += 1 + l + sovMonitor(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *NodeStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DiskAvailable != 0 {
		n += 1 + sovMonitor(uint64(m.DiskAvailable))
	}
	if m.DiskTotal != 0 {
		n += 1 + sovMonitor(uint64(m.DiskTotal))
	}
	if m.NetworkSpeed != 0 {
		n += 1 + sovMonitor(uint64(m.NetworkSpeed))
	}
	if m.CpuPercent != 0 {
		n += 9
	}
	if m.MemoryUsage != 0 {
		n += 1 + sovMonitor(uint64(m.MemoryUsage))
	}
	if m.MemoryTotal != 0 {
		n += 1 + sovMonitor(uint64(m.MemoryTotal))
	}
	if m.BlockCount != 0 {
		n += 1 + sovMonitor(uint64(m.BlockCount))
	}
	if m.MetaCount != 0 {
		n += 1 + sovMonitor(uint64(m.MetaCount))
	}
	if m.GoroutineCount != 0 {
		n += 1 + sovMonitor(uint64(m.GoroutineCount))
	}
	if m.MetaPipelineCount != 0 {
		n += 1 + sovMonitor(uint64(m.MetaPipelineCount))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PipelineReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PgId != 0 {
		n += 1 + sovMonitor(uint64(m.PgId))
	}
	if len(m.NodeIds) > 0 {
		l = 0
		for _, e := range m.NodeIds {
			l += sovMonitor(uint64(e))
		}
		n += 1 + sovMonitor(uint64(l)) + l
	}
	if m.State != 0 {
		n += 1 + sovMonitor(uint64(m.State))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ClusterReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.State != 0 {
		n += 1 + sovMonitor(uint64(m.State))
	}
	if m.ClusterInfo != nil {
		l = m.ClusterInfo.Size()
		n += 1 + l + sovMonitor(uint64(l))
	}
	if len(m.Nodes) > 0 {
		for _, e := range m.Nodes {
			l = e.Size()
			n += 1 + l + sovMonitor(uint64(l))
		}
	}
	if len(m.Pipelines) > 0 {
		for _, e := range m.Pipelines {
			l = e.Size()
			n += 1 + l + sovMonitor(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *StateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovMonitor(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMonitor(x uint64) (n int) {
	return sovMonitor(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NodeStatusReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonitor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeStatusReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeStatusReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			m.NodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeUuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMonitor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMonitor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeUuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonitor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMonitor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Timestamp == nil {
				m.Timestamp = &timestamp.Timestamp{}
			}
			if err := m.Timestamp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= infos.NodeState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonitor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMonitor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Status == nil {
				m.Status = &NodeStatus{}
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
			}
			m.Role = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Role |= NodeStatusReport_Role(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pipelines", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonitor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMonitor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pipelines = append(m.Pipelines, &PipelineReport{})
			if err := m.Pipelines[len(m.Pipelines)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMonitor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonitor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonitor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiskAvailable", wireType)
			}
			m.DiskAvailable = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DiskAvailable |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiskTotal", wireType)
			}
			m.DiskTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DiskTotal |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkSpeed", wireType)
			}
			m.NetworkSpeed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NetworkSpeed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field CpuPercent", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.CpuPercent = float64(math.Float64frombits(v))
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryUsage", wireType)
			}
			m.MemoryUsage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemoryUsage |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryTotal", wireType)
			}
			m.MemoryTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemoryTotal |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockCount", wireType)
			}
			m.BlockCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetaCount", wireType)
			}
			m.MetaCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MetaCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoroutineCount", wireType)
			}
			m.GoroutineCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GoroutineCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetaPipelineCount", wireType)
			}
			m.MetaPipelineCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MetaPipelineCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMonitor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonitor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PipelineReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonitor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PipelineReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PipelineReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PgId", wireType)
			}
			m.PgId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PgId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMonitor
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.NodeIds = append(m.NodeIds, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMonitor
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthMonitor
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthMonitor
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.NodeIds) == 0 {
					m.NodeIds = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMonitor
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.NodeIds = append(m.NodeIds, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeIds", wireType)
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= PipelineReport_State(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMonitor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonitor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonitor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= ClusterReport_ClusterState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonitor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMonitor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ClusterInfo == nil {
				m.ClusterInfo = &infos.ClusterInfo{}
			}
			if err := m.ClusterInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonitor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMonitor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nodes = append(m.Nodes, &NodeStatusReport{})
			if err := m.Nodes[len(m.Nodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pipelines", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonitor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMonitor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pipelines = append(m.Pipelines, &PipelineReport{})
			if err := m.Pipelines[len(m.Pipelines)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMonitor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonitor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonitor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMonitor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonitor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMonitor(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMonitor
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMonitor
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMonitor
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMonitor
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMonitor        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMonitor          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMonitor = fmt.Errorf("proto: unexpected end of group")
)
