// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: pipline.proto

package pipline

import (
	_ "ecos/messenger/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pipline_SyncType int32

const (
	Pipline_RAFT   Pipline_SyncType = 0
	Pipline_STREAM Pipline_SyncType = 1
)

// Enum value maps for Pipline_SyncType.
var (
	Pipline_SyncType_name = map[int32]string{
		0: "RAFT",
		1: "STREAM",
	}
	Pipline_SyncType_value = map[string]int32{
		"RAFT":   0,
		"STREAM": 1,
	}
)

func (x Pipline_SyncType) Enum() *Pipline_SyncType {
	p := new(Pipline_SyncType)
	*p = x
	return p
}

func (x Pipline_SyncType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Pipline_SyncType) Descriptor() protoreflect.EnumDescriptor {
	return file_pipline_proto_enumTypes[0].Descriptor()
}

func (Pipline_SyncType) Type() protoreflect.EnumType {
	return &file_pipline_proto_enumTypes[0]
}

func (x Pipline_SyncType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Pipline_SyncType.Descriptor instead.
func (Pipline_SyncType) EnumDescriptor() ([]byte, []int) {
	return file_pipline_proto_rawDescGZIP(), []int{0, 0}
}

type Pipline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PgId     uint64           `protobuf:"varint,1,opt,name=pg_id,json=pgId,proto3" json:"pg_id,omitempty"`
	RaftId   []uint64         `protobuf:"varint,2,rep,packed,name=raft_id,json=raftId,proto3" json:"raft_id,omitempty"`
	SyncType Pipline_SyncType `protobuf:"varint,3,opt,name=sync_type,json=syncType,proto3,enum=messenger.Pipline_SyncType" json:"sync_type,omitempty"`
}

func (x *Pipline) Reset() {
	*x = Pipline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pipline_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pipline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipline) ProtoMessage() {}

func (x *Pipline) ProtoReflect() protoreflect.Message {
	mi := &file_pipline_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipline.ProtoReflect.Descriptor instead.
func (*Pipline) Descriptor() ([]byte, []int) {
	return file_pipline_proto_rawDescGZIP(), []int{0}
}

func (x *Pipline) GetPgId() uint64 {
	if x != nil {
		return x.PgId
	}
	return 0
}

func (x *Pipline) GetRaftId() []uint64 {
	if x != nil {
		return x.RaftId
	}
	return nil
}

func (x *Pipline) GetSyncType() Pipline_SyncType {
	if x != nil {
		return x.SyncType
	}
	return Pipline_RAFT
}

var File_pipline_proto protoreflect.FileDescriptor

var file_pipline_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x69, 0x70, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x01, 0x0a, 0x07, 0x50, 0x69, 0x70,
	0x6c, 0x69, 0x6e, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x70, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x70, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x61, 0x66,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x72, 0x61, 0x66, 0x74,
	0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65,
	0x72, 0x2e, 0x50, 0x69, 0x70, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x08, 0x73, 0x79, 0x6e, 0x63, 0x54, 0x79, 0x70, 0x65, 0x22, 0x20, 0x0a, 0x08,
	0x53, 0x79, 0x6e, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x41, 0x46, 0x54,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x10, 0x01, 0x42, 0x18,
	0x5a, 0x16, 0x65, 0x63, 0x6f, 0x73, 0x2f, 0x65, 0x64, 0x67, 0x65, 0x2d, 0x6e, 0x6f, 0x64, 0x65,
	0x2f, 0x70, 0x69, 0x70, 0x6c, 0x69, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pipline_proto_rawDescOnce sync.Once
	file_pipline_proto_rawDescData = file_pipline_proto_rawDesc
)

func file_pipline_proto_rawDescGZIP() []byte {
	file_pipline_proto_rawDescOnce.Do(func() {
		file_pipline_proto_rawDescData = protoimpl.X.CompressGZIP(file_pipline_proto_rawDescData)
	})
	return file_pipline_proto_rawDescData
}

var file_pipline_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pipline_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pipline_proto_goTypes = []interface{}{
	(Pipline_SyncType)(0), // 0: messenger.Pipline.SyncType
	(*Pipline)(nil),       // 1: messenger.Pipline
}
var file_pipline_proto_depIdxs = []int32{
	0, // 0: messenger.Pipline.sync_type:type_name -> messenger.Pipline.SyncType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pipline_proto_init() }
func file_pipline_proto_init() {
	if File_pipline_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pipline_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pipline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pipline_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pipline_proto_goTypes,
		DependencyIndexes: file_pipline_proto_depIdxs,
		EnumInfos:         file_pipline_proto_enumTypes,
		MessageInfos:      file_pipline_proto_msgTypes,
	}.Build()
	File_pipline_proto = out.File
	file_pipline_proto_rawDesc = nil
	file_pipline_proto_goTypes = nil
	file_pipline_proto_depIdxs = nil
}
