// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gaia.proto

package gaia

import (
	object "ecos/edge-node/object"
	pipeline "ecos/edge-node/pipeline"
	_ "ecos/messenger/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ControlMessage_Code int32

const (
	ControlMessage_BEGIN ControlMessage_Code = 0
	ControlMessage_EOF   ControlMessage_Code = 1
)

var ControlMessage_Code_name = map[int32]string{
	0: "BEGIN",
	1: "EOF",
}

var ControlMessage_Code_value = map[string]int32{
	"BEGIN": 0,
	"EOF":   1,
}

func (x ControlMessage_Code) String() string {
	return proto.EnumName(ControlMessage_Code_name, int32(x))
}

func (ControlMessage_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b6e644bf26c0761, []int{1, 0}
}

type UploadBlockRequest struct {
	// Types that are valid to be assigned to Payload:
	//	*UploadBlockRequest_Chunk
	//	*UploadBlockRequest_Message
	Payload              isUploadBlockRequest_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *UploadBlockRequest) Reset()         { *m = UploadBlockRequest{} }
func (m *UploadBlockRequest) String() string { return proto.CompactTextString(m) }
func (*UploadBlockRequest) ProtoMessage()    {}
func (*UploadBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b6e644bf26c0761, []int{0}
}
func (m *UploadBlockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UploadBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UploadBlockRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UploadBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadBlockRequest.Merge(m, src)
}
func (m *UploadBlockRequest) XXX_Size() int {
	return m.Size()
}
func (m *UploadBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadBlockRequest proto.InternalMessageInfo

type isUploadBlockRequest_Payload interface {
	isUploadBlockRequest_Payload()
	MarshalTo([]byte) (int, error)
	Size() int
}

type UploadBlockRequest_Chunk struct {
	Chunk *Chunk `protobuf:"bytes,1,opt,name=chunk,proto3,oneof" json:"chunk,omitempty"`
}
type UploadBlockRequest_Message struct {
	Message *ControlMessage `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
}

func (*UploadBlockRequest_Chunk) isUploadBlockRequest_Payload()   {}
func (*UploadBlockRequest_Message) isUploadBlockRequest_Payload() {}

func (m *UploadBlockRequest) GetPayload() isUploadBlockRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UploadBlockRequest) GetChunk() *Chunk {
	if x, ok := m.GetPayload().(*UploadBlockRequest_Chunk); ok {
		return x.Chunk
	}
	return nil
}

func (m *UploadBlockRequest) GetMessage() *ControlMessage {
	if x, ok := m.GetPayload().(*UploadBlockRequest_Message); ok {
		return x.Message
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UploadBlockRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UploadBlockRequest_Chunk)(nil),
		(*UploadBlockRequest_Message)(nil),
	}
}

type ControlMessage struct {
	Code                 ControlMessage_Code `protobuf:"varint,1,opt,name=code,proto3,enum=messenger.ControlMessage_Code" json:"code,omitempty"`
	Block                *object.BlockInfo   `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	Pipeline             *pipeline.Pipeline  `protobuf:"bytes,3,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Term                 uint64              `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ControlMessage) Reset()         { *m = ControlMessage{} }
func (m *ControlMessage) String() string { return proto.CompactTextString(m) }
func (*ControlMessage) ProtoMessage()    {}
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b6e644bf26c0761, []int{1}
}
func (m *ControlMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ControlMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ControlMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ControlMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlMessage.Merge(m, src)
}
func (m *ControlMessage) XXX_Size() int {
	return m.Size()
}
func (m *ControlMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ControlMessage proto.InternalMessageInfo

func (m *ControlMessage) GetCode() ControlMessage_Code {
	if m != nil {
		return m.Code
	}
	return ControlMessage_BEGIN
}

func (m *ControlMessage) GetBlock() *object.BlockInfo {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *ControlMessage) GetPipeline() *pipeline.Pipeline {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

func (m *ControlMessage) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

type Chunk struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b6e644bf26c0761, []int{2}
}
func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return m.Size()
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterEnum("messenger.ControlMessage_Code", ControlMessage_Code_name, ControlMessage_Code_value)
	proto.RegisterType((*UploadBlockRequest)(nil), "messenger.UploadBlockRequest")
	proto.RegisterType((*ControlMessage)(nil), "messenger.ControlMessage")
	proto.RegisterType((*Chunk)(nil), "messenger.Chunk")
}

func init() { proto.RegisterFile("gaia.proto", fileDescriptor_2b6e644bf26c0761) }

var fileDescriptor_2b6e644bf26c0761 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0xae, 0x93, 0x40,
	0x14, 0xc6, 0x19, 0x0b, 0x62, 0x8f, 0x4d, 0xad, 0x53, 0x17, 0x48, 0x22, 0xa9, 0x24, 0x26, 0xc4,
	0x44, 0x9a, 0x60, 0x7c, 0x01, 0x6a, 0x6d, 0xbb, 0xd0, 0x9a, 0x49, 0xdc, 0xb8, 0x9b, 0xc2, 0x11,
	0xb1, 0x30, 0x83, 0x30, 0x5d, 0xb8, 0xf3, 0x31, 0x7c, 0x24, 0x97, 0xfa, 0x06, 0x37, 0xbd, 0x2f,
	0x72, 0xc3, 0xd0, 0x36, 0xdc, 0xdc, 0xdc, 0xdd, 0x9c, 0xf9, 0x7e, 0x73, 0xfe, 0x7d, 0x03, 0x90,
	0xf1, 0x9c, 0x87, 0x55, 0x2d, 0x95, 0xa4, 0xc3, 0x12, 0x9b, 0x06, 0x45, 0x86, 0xb5, 0x3b, 0x4a,
	0x64, 0x59, 0x4a, 0xd1, 0x09, 0xee, 0x48, 0xee, 0x7e, 0x60, 0xa2, 0x4e, 0xd1, 0xb8, 0xca, 0x2b,
	0x2c, 0x72, 0x81, 0x5d, 0xec, 0xff, 0x26, 0x40, 0xbf, 0x54, 0x85, 0xe4, 0x69, 0x5c, 0xc8, 0x64,
	0xcf, 0xf0, 0xe7, 0x01, 0x1b, 0x45, 0x03, 0xb0, 0x92, 0xef, 0x07, 0xb1, 0x77, 0xc8, 0x8c, 0x04,
	0x8f, 0xa3, 0x49, 0x78, 0xc9, 0x1e, 0x2e, 0xda, 0xfb, 0xb5, 0xc1, 0x3a, 0x80, 0xbe, 0x03, 0xbb,
	0xd5, 0x78, 0x86, 0xce, 0x03, 0xcd, 0x3e, 0xef, 0xb3, 0x52, 0xa8, 0x5a, 0x16, 0x1f, 0x3b, 0x60,
	0x6d, 0xb0, 0x33, 0x1b, 0x0f, 0xc1, 0xae, 0xf8, 0xaf, 0xb6, 0xae, 0xff, 0x9f, 0xc0, 0xf8, 0x36,
	0x48, 0x23, 0x30, 0x13, 0x99, 0xa2, 0xae, 0x3e, 0x8e, 0xbc, 0x7b, 0x33, 0x86, 0x0b, 0x99, 0x22,
	0xd3, 0x2c, 0x7d, 0x0d, 0xd6, 0xae, 0x1d, 0xe1, 0xd4, 0xc6, 0xb3, 0xde, 0x23, 0x3d, 0xda, 0x46,
	0x7c, 0x93, 0xac, 0x43, 0xe8, 0x1c, 0x1e, 0x9d, 0xf7, 0xe0, 0x0c, 0x34, 0x3e, 0xed, 0xe1, 0x9f,
	0x4f, 0x12, 0xbb, 0x40, 0x94, 0x82, 0xa9, 0xb0, 0x2e, 0x1d, 0x73, 0x46, 0x02, 0x93, 0xe9, 0xb3,
	0xef, 0x82, 0xd9, 0x96, 0xa7, 0x43, 0xb0, 0xe2, 0xe5, 0x6a, 0xf3, 0x69, 0x62, 0x50, 0x1b, 0x06,
	0xcb, 0xed, 0x87, 0x09, 0xf1, 0x5f, 0x82, 0xa5, 0xf7, 0x44, 0x1d, 0xb0, 0x13, 0x29, 0x14, 0x0a,
	0xa5, 0x87, 0x19, 0xb1, 0x73, 0x18, 0x6d, 0xc1, 0x5c, 0xf1, 0x9c, 0xd3, 0x15, 0x3c, 0xe9, 0x19,
	0xf0, 0x9e, 0x2b, 0x4e, 0x5f, 0xf4, 0x9a, 0xb9, 0x6b, 0x8e, 0xfb, 0xb4, 0x27, 0x33, 0x6c, 0x0e,
	0x85, 0xf2, 0x8d, 0x80, 0xc4, 0xaf, 0xfe, 0x1e, 0x3d, 0xf2, 0xef, 0xe8, 0x91, 0xab, 0xa3, 0x47,
	0xfe, 0x5c, 0x7b, 0xc6, 0xd7, 0x29, 0x26, 0xb2, 0x99, 0x63, 0x9a, 0xe1, 0x1b, 0x21, 0x53, 0x9c,
	0xb7, 0xdf, 0x65, 0xf7, 0x50, 0x1b, 0xff, 0xf6, 0x26, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x60, 0x03,
	0xe1, 0x3d, 0x02, 0x00, 0x00,
}

func (m *UploadBlockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UploadBlockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UploadBlockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Payload != nil {
		{
			size := m.Payload.Size()
			i -= size
			if _, err := m.Payload.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *UploadBlockRequest_Chunk) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UploadBlockRequest_Chunk) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Chunk != nil {
		{
			size, err := m.Chunk.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGaia(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *UploadBlockRequest_Message) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UploadBlockRequest_Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Message != nil {
		{
			size, err := m.Message.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGaia(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *ControlMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ControlMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ControlMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Term != 0 {
		i = encodeVarintGaia(dAtA, i, uint64(m.Term))
		i--
		dAtA[i] = 0x20
	}
	if m.Pipeline != nil {
		{
			size, err := m.Pipeline.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGaia(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Block != nil {
		{
			size, err := m.Block.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGaia(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Code != 0 {
		i = encodeVarintGaia(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Chunk) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Chunk) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Chunk) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Content) > 0 {
		i -= len(m.Content)
		copy(dAtA[i:], m.Content)
		i = encodeVarintGaia(dAtA, i, uint64(len(m.Content)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGaia(dAtA []byte, offset int, v uint64) int {
	offset -= sovGaia(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UploadBlockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Payload != nil {
		n += m.Payload.Size()
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UploadBlockRequest_Chunk) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Chunk != nil {
		l = m.Chunk.Size()
		n += 1 + l + sovGaia(uint64(l))
	}
	return n
}
func (m *UploadBlockRequest_Message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Message != nil {
		l = m.Message.Size()
		n += 1 + l + sovGaia(uint64(l))
	}
	return n
}
func (m *ControlMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovGaia(uint64(m.Code))
	}
	if m.Block != nil {
		l = m.Block.Size()
		n += 1 + l + sovGaia(uint64(l))
	}
	if m.Pipeline != nil {
		l = m.Pipeline.Size()
		n += 1 + l + sovGaia(uint64(l))
	}
	if m.Term != 0 {
		n += 1 + sovGaia(uint64(m.Term))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Chunk) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovGaia(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovGaia(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGaia(x uint64) (n int) {
	return sovGaia(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UploadBlockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGaia
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UploadBlockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UploadBlockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chunk", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGaia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGaia
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGaia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Chunk{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Payload = &UploadBlockRequest_Chunk{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGaia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGaia
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGaia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ControlMessage{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Payload = &UploadBlockRequest_Message{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGaia(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGaia
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ControlMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGaia
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ControlMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ControlMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGaia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= ControlMessage_Code(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGaia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGaia
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGaia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Block == nil {
				m.Block = &object.BlockInfo{}
			}
			if err := m.Block.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pipeline", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGaia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGaia
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGaia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pipeline == nil {
				m.Pipeline = &pipeline.Pipeline{}
			}
			if err := m.Pipeline.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Term", wireType)
			}
			m.Term = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGaia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Term |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGaia(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGaia
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Chunk) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGaia
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Chunk: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Chunk: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGaia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGaia
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGaia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = append(m.Content[:0], dAtA[iNdEx:postIndex]...)
			if m.Content == nil {
				m.Content = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGaia(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGaia
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGaia(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGaia
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGaia
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGaia
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGaia
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGaia
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGaia
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGaia        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGaia          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGaia = fmt.Errorf("proto: unexpected end of group")
)
